# Generated by Django 4.1.2 on 2023-06-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_tools"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="tools_images"),
        ),
    ]
