# Generated by Django 4.1.2 on 2023-06-17 12:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_quillpost_post_quill_full_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
