# Generated by Django 4.1.2 on 2023-06-14 10:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_post_tinymce'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_quill',
            name='my_field',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
