# Generated by Django 4.1.2 on 2023-06-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='level',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
