# Generated by Django 4.1.2 on 2023-06-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_jobs_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='persian_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
