# Generated by Django 4.1.2 on 2023-06-18 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_profile_job_position_alter_jobs_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_position',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_position', to='users.jobs'),
        ),
    ]
