# Generated by Django 4.1.2 on 2023-06-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='short_name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
