# Generated by Django 4.1.2 on 2023-06-19 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_alter_jobs_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('persian_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=3, unique=True)),
                ('start_date', models.DateTimeField()),
                ('describe', models.CharField(max_length=800)),
                ('project_maanger', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-short_name'],
            },
        ),
    ]
