# Generated by Django 4.1.2 on 2023-06-19 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_cities_alter_projects_project_maanger'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='city',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_city', to='users.cities'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_maanger',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
