# Generated by Django 4.1.2 on 2023-07-07 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_projects_short_name_phonebook"),
        ("users", "0021_alter_projects_short_name_phonebook"),
    ]

    operations = []
