# Generated by Django 4.1.2 on 2023-07-07 17:49

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_phonebook_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonebook",
            name="phone_number",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
    ]
