# Generated by Django 4.1.2 on 2023-07-07 17:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_alter_phonebook_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonebook",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="phonebook",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="", max_length=128, region=None, unique=True
            ),
            preserve_default=False,
        ),
    ]
