# Generated by Django 4.2.13 on 2024-05-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_phonebook_phone_number_phonebook_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='raw_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=800)),
                ('unit', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-unit'],
            },
        ),
    ]
