# Generated by Django 4.2.13 on 2024-05-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_raw_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raw_material',
            old_name='name_material',
            new_name='name',
        ),
    ]
