# Generated by Django 4.2.13 on 2024-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_create_order_new_create_order_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mother_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('describe', models.CharField(max_length=800)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.AlterModelOptions(
            name='raw_material',
            options={'ordering': ['-name']},
        ),
    ]
