# Generated by Django 4.2.13 on 2024-05-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_raw_material_mother'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tools',
            name='status',
        ),
    ]
