# Generated by Django 4.2.13 on 2024-05-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_remove_tools_content_remove_tools_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
