# Generated by Django 4.2.13 on 2024-05-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_foodfilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnappFoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=20000)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_name', to='users.cities')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
