# Generated by Django 4.2.13 on 2024-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_foodrawmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
