# Generated by Django 5.0.7 on 2024-07-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_foodrawmaterial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='mother_food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
