# Generated by Django 5.0.7 on 2024-07-27 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_mother_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrawmaterial',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_food', to='users.mother_food'),
        ),
    ]
