# Generated by Django 5.0.7 on 2024-07-27 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_foodrawmaterial_mother'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrawmaterial',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_food_id', to='users.mother_food'),
        ),
    ]
