# Generated by Django 5.0.7 on 2024-07-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_foodrawmaterial_mother'),
    ]

    operations = [
        migrations.CreateModel(
            name='mode_raw_materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
