# Generated by Django 5.0.7 on 2024-07-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_raw_material_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother_material',
            name='mode',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mode_raw_materials_mother_material', to='users.mode_raw_materials'),
        ),
    ]
