# Generated by Django 5.0.7 on 2024-07-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_mother_material_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create_order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='create_order',
            name='night_order',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
