# Generated by Django 5.0.7 on 2024-08-31 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_alter_create_order_options_create_order_night_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
