# Generated by Django 5.0.7 on 2024-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_warehouse_alter_mother_material_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
