# Generated by Django 5.0.7 on 2024-09-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_warehouse_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='users.warehouse'),
        ),
    ]
