# Generated by Django 5.0.7 on 2024-09-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_inventorylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='last_user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_inventory_log', to='users.profile'),
        ),
    ]
