# Generated by Django 5.0.7 on 2024-10-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_inventory_last_user_alter_inventorylog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='last_user',
        ),
        migrations.CreateModel(
            name='NightOrderRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remainder_night_order', models.CharField(blank=True, max_length=20000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_order_remainders', to='users.create_order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_order_remainders', to='users.restaurantbranch')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
