# Generated by Django 4.1.2 on 2023-06-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_post_quill'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_quill',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=False),
            preserve_default=False,
        ),
    ]
