# Generated by Django 4.1.2 on 2023-06-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_post_quill_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_quill',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post_quill',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
