# Generated by Django 4.1.2 on 2023-06-14 11:40

from django.db import migrations, models
import django_quill.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_post_quill_my_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='tinymce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AlterField(
            model_name='quillpost',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
