# Generated by Django 4.1.2 on 2023-06-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_post_quill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_quill',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
