# Generated by Django 4.1.2 on 2023-06-13 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_alter_post_quill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_quill',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_quil', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
