# Generated by Django 4.1.2 on 2023-06-13 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0020_alter_post_quill_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_quill',
            name='author',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts_quil', to=settings.AUTH_USER_MODEL),
        ),
    ]
