# Generated by Django 5.0.7 on 2024-07-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_mode_raw_materials_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_material',
            name='mode',
        ),
    ]
